// Complete Teletalk District mapping (64 districts)
const DISTRICT_TO_CODE = {
  "bagerhat": "26",
  "bandarban": "64",
  "barguna": "32",
  "barishal": "29",
  "bhola": "30",
  "bogura": "10",
  "brahmanbaria": "54",
  "chandpur": "56",
  "chapai nawabganj": "13",
  "chattogram": "60",
  "chuadanga": "19",
  "cox`s bazar": "61",
  "cumilla": "55",
  "dhaka": "40",
  "dinajpur": "03",
  "faridpur": "45",
  "feni": "59",
  "gaibandha": "08",
  "gazipur": "41",
  "gopalganj": "47",
  "habiganj": "53",
  "jamalpur": "36",
  "jashore": "23",
  "jhalakathi": "28",
  "jhenaidah": "20",
  "joypurhat": "09",
  "khagrachhari": "62",
  "khulna": "25",
  "kishoreganj": "38",
  "kurigram": "07",
  "kushtia": "17",
  "lakshmipur": "57",
  "lalmonirhat": "05",
  "madaripur": "48",
  "magura": "21",
  "manikganj": "39",
  "meherpur": "18",
  "moulvibazar": "52",
  "munshiganj": "44",
  "mymensingh": "34",
  "naogaon": "11",
  "narail": "22",
  "narayanganj": "43",
  "narsingdi": "42",
  "natore": "12",
  "netrokona": "33",
  "nilphamari": "04",
  "noakhali": "58",
  "pabna": "16",
  "panchagarh": "01",
  "patuakhali": "31",
  "pirojpur": "27",
  "rajbari": "46",
  "rajshahi": "14",
  "rangamati": "63",
  "rangpur": "06",
  "satkhira": "24",
  "shariatpur": "49",
  "sherpur": "35",
  "sirajganj": "15",
  "sunamganj": "50",
  "sylhet": "51",
  "tangail": "37",
  "thakurgaon": "02"
};

// Complete Upazila mapping by District Code
const UPAZILA_MAP = {
  "55": [
    "Barura",
    "Brahmanpara",
    "Burichang",
    "Chandina",
    "Chauddagram",
    "Comilla Sadar",
    "Daudkandi",
    "Debidwar",
    "Homna",
    "Laksam",
    "Lalmai",
    "Meghna",
    "Monohargonj",
    "Muradnagar",
    "Nangalkot",
    "Sadarsouth",
    "Titas"
  ],
  "59": [
    "Chhagalnaiya",
    "Daganbhuiyan",
    "Feni Sadar",
    "Fulgazi",
    "Parshuram",
    "Sonagazi"
  ],
  "54": [
    "Akhaura",
    "Ashuganj",
    "Bancharampur",
    "Bijoynagar",
    "Brahmanbaria Sadar",
    "Kasba",
    "Nabinagar",
    "Nasirnagar",
    "Sarail"
  ],
  "63": [
    "Baghaichari",
    "Barkal",
    "Belaichari",
    "Juraichari",
    "Kaptai",
    "Kawkhali",
    "Langadu",
    "Naniarchar",
    "Rajasthali",
    "Rangamati Sadar"
  ],
  "58": [
    "Begumganj",
    "Chatkhil",
    "Companiganj",
    "Hatia",
    "Kabirhat",
    "Noakhali Sadar",
    "Senbug",
    "Sonaimori",
    "Subarnachar"
  ],
  "56": [
    "Chandpur Sadar",
    "Faridgonj",
    "Haimchar",
    "Hajiganj",
    "Kachua",
    "Matlab North",
    "Matlab South",
    "Shahrasti"
  ],
  "57": [
    "Kamalnagar",
    "Lakshmipur Sadar",
    "Raipur",
    "Ramganj",
    "Ramgati"
  ],
  "60": [
    "Akbar Shah",
    "Anwara",
    "Bakalia",
    "Banshkhali",
    "Bayazid Bostami",
    "Boalkhali",
    "Chandanaish",
    "Double Mooring",
    "EPZ",
    "Fatikchhari",
    "Halishahar",
    "Hathazari",
    "Karnafuli",
    "Khulshi",
    "Lohagara",
    "Mirsharai",
    "Pahartali",
    "Panchlaish",
    "Patenga",
    "Patiya",
    "Rangunia",
    "Raozan",
    "Sandwip",
    "Satkania",
    "Sitakunda"
  ],
  "61": [
    "Chakaria",
    "Coxsbazar Sadar",
    "Eidgaon",
    "Kutubdia",
    "Moheshkhali",
    "Pekua",
    "Ramu",
    "Teknaf",
    "Ukhiya"
  ],
  "62": [
    "Dighinala",
    "Guimara",
    "Khagrachhari Sadar",
    "Laxmichhari",
    "Manikchari",
    "Matiranga",
    "Mohalchari",
    "Panchari",
    "Ramgarh"
  ],
  "64": [
    "Alikadam",
    "Bandarban Sadar",
    "Lama",
    "Naikhongchhari",
    "Rowangchhari",
    "Ruma",
    "Thanchi"
  ],
  "15": [
    "Belkuchi",
    "Chauhali",
    "Kamarkhand",
    "Kazipur",
    "Raigonj",
    "Shahjadpur",
    "Sirajganj Sadar",
    "Tarash",
    "Ullapara"
  ],
  "16": [
    "Atghoria",
    "Bera",
    "Bhangura",
    "Chatmohar",
    "Faridpur",
    "Ishurdi",
    "Pabna Sadar",
    "Santhia",
    "Sujanagar"
  ],
  "10": [
    "Adamdighi",
    "Bogra Sadar",
    "Dhunot",
    "Dupchanchia",
    "Gabtali",
    "Kahaloo",
    "Nondigram",
    "Shajahanpur",
    "Shariakandi",
    "Sherpur",
    "Shibganj",
    "Sonatala"
  ],
  "14": [
    "Bagha",
    "Bagmara",
    "Charghat",
    "Durgapur",
    "Godagari",
    "Mohonpur",
    "Paba",
    "Puthia",
    "Tanore"
  ],
  "12": [
    "Bagatipara",
    "Baraigram",
    "Gurudaspur",
    "Lalpur",
    "Naldanga",
    "Natore Sadar",
    "Singra"
  ],
  "09": [
    "Akkelpur",
    "Joypurhat Sadar",
    "Kalai",
    "Khetlal",
    "Panchbibi"
  ],
  "13": [
    "Bholahat",
    "Chapainawabganj Sadar",
    "Gomostapur",
    "Nachol",
    "Shibganj"
  ],
  "11": [
    "Atrai",
    "Badalgachi",
    "Dhamoirhat",
    "Manda",
    "Mohadevpur",
    "Naogaon Sadar",
    "Niamatpur",
    "Patnitala",
    "Porsha",
    "Raninagar",
    "Sapahar"
  ],
  "23": [
    "Abhaynagar",
    "Bagherpara",
    "Chougachha",
    "Jessore Sadar",
    "Jhikargacha",
    "Keshabpur",
    "Manirampur",
    "Sharsha"
  ],
  "24": [
    "Assasuni",
    "Debhata",
    "Kalaroa",
    "Kaliganj",
    "Satkhira Sadar",
    "Shyamnagar",
    "Tala"
  ],
  "18": [
    "Gangni",
    "Meherpur Sadar",
    "Mujibnagar"
  ],
  "22": [
    "Kalia",
    "Lohagara",
    "Narail Sadar"
  ],
  "19": [
    "Alamdanga",
    "Chuadanga Sadar",
    "Damurhuda",
    "Jibannagar"
  ],
  "17": [
    "Bheramara",
    "Daulatpur",
    "Khoksa",
    "Kumarkhali",
    "Kushtia Sadar",
    "Mirpur"
  ],
  "21": [
    "Magura Sadar",
    "Mohammadpur",
    "Shalikha",
    "Sreepur"
  ],
  "25": [
    "Botiaghata",
    "Dakop",
    "Digholia",
    "Dumuria",
    "Fultola",
    "Koyra",
    "Paikgasa",
    "Rupsha",
    "Terokhada"
  ],
  "26": [
    "Bagerhat Sadar",
    "Chitalmari",
    "Fakirhat",
    "Kachua",
    "Mollahat",
    "Mongla",
    "Morrelganj",
    "Rampal",
    "Sarankhola"
  ],
  "20": [
    "Harinakundu",
    "Jhenaidah Sadar",
    "Kaliganj",
    "Kotchandpur",
    "Moheshpur",
    "Shailkupa"
  ],
  "28": [
    "Jhalakathi Sadar",
    "Kathalia",
    "Nalchity",
    "Rajapur"
  ],
  "31": [
    "Bauphal",
    "Dashmina",
    "Dumki",
    "Galachipa",
    "Kalapara",
    "Mirzaganj",
    "Patuakhali Sadar",
    "Rangabali"
  ],
  "27": [
    "Bhandaria",
    "Kawkhali",
    "Mathbaria",
    "Nazirpur",
    "Nesarabad",
    "Pirojpur Sadar",
    "Zianagar"
  ],
  "29": [
    "Agailjhara",
    "Babuganj",
    "Bakerganj",
    "Banaripara",
    "Barisal Sadar",
    "Gournadi",
    "Hizla",
    "Mehendiganj",
    "Muladi",
    "Wazirpur"
  ],
  "30": [
    "Bhola Sadar",
    "Borhan Sddin",
    "Charfesson",
    "Doulatkhan",
    "Lalmohan",
    "Monpura",
    "Tazumuddin"
  ],
  "32": [
    "Amtali",
    "Bamna",
    "Barguna Sadar",
    "Betagi",
    "Pathorghata",
    "Taltali"
  ],
  "51": [
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companiganj",
    "Dakshinsurma",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Kanaighat",
    "Osmaninagar",
    "Sylhet Sadar",
    "Zakiganj"
  ],
  "52": [
    "Barlekha",
    "Juri",
    "Kamolganj",
    "Kulaura",
    "Moulvibazar Sadar",
    "Rajnagar",
    "Sreemangal"
  ],
  "53": [
    "Ajmiriganj",
    "Bahubal",
    "Baniachong",
    "Chunarughat",
    "Habiganj Sadar",
    "Lakhai",
    "Madhabpur",
    "Nabiganj"
  ],
  "50": [
    "Bishwambarpur",
    "Chhatak",
    "Derai",
    "Dharmapasha",
    "Dowarabazar",
    "Jagannathpur",
    "Jamalganj",
    "Madhyanagar",
    "Shalla",
    "South Sunamganj",
    "Sunamganj Sadar",
    "Tahirpur"
  ],
  "42": [
    "Belabo",
    "Monohardi",
    "Narsingdi Sadar",
    "Palash",
    "Raipura",
    "Shibpur"
  ],
  "41": [
    "Gazipur Sadar",
    "Kaliakair",
    "Kaliganj",
    "Kapasia",
    "Sreepur"
  ],
  "49": [
    "Bhedarganj",
    "Damudya",
    "Gosairhat",
    "Naria",
    "Shariatpur Sadar",
    "Zajira"
  ],
  "43": [
    "Araihazar",
    "Bandar",
    "Narayanganj Sadar",
    "Rupganj",
    "Sonargaon"
  ],
  "37": [
    "Basail",
    "Bhuapur",
    "Delduar",
    "Dhanbari",
    "Ghatail",
    "Gopalpur",
    "Kalihati",
    "Madhupur",
    "Mirzapur",
    "Nagarpur",
    "Sakhipur",
    "Tangail Sadar"
  ],
  "38": [
    "Austagram",
    "Bajitpur",
    "Bhairab",
    "Hossainpur",
    "Itna",
    "Karimgonj",
    "Katiadi",
    "Kishoreganj Sadar",
    "Kuliarchar",
    "Mithamoin",
    "Nikli",
    "Pakundia",
    "Tarail"
  ],
  "39": [
    "Doulatpur",
    "Gior",
    "Harirampur",
    "Manikganj Sadar",
    "Saturia",
    "Shibaloy",
    "Singiar"
  ],
  "40": [
    "Adabor",
    "Airport",
    "Badda",
    "Banani",
    "Bangshal",
    "Bhashantek",
    "Cantonment",
    "Chackbazar",
    "Dakshin Khan",
    "Darus-Salam",
    "Demra",
    "Dhamrai",
    "Dhanmondi",
    "Dohar",
    "Gandaria",
    "Gulshan",
    "Hatirjheel",
    "Hazaribagh",
    "Jatrabari",
    "Kafrul",
    "Kalabagan",
    "Kamrangirchar",
    "Keraniganj",
    "Khilgaon",
    "Khilkhet",
    "Kotwali",
    "Lalbagh",
    "Mirpur",
    "Mohammadpur",
    "Motijheel",
    "Mugda",
    "Nawabganj",
    "New Market",
    "Pallabi",
    "Paltan",
    "Ramna",
    "Rampura",
    "Rupnagar",
    "Sabujbagh",
    "Savar",
    "Shah Ali",
    "Shahbagh",
    "Sher-e-Bangla Nagar",
    "Shyampur",
    "Sutrapur",
    "Tejgaon",
    "Tejgaon Industrial Area",
    "Turag",
    "Uttar Khan",
    "Uttara East",
    "Uttara West",
    "Vasantek",
    "Wari"
  ],
  "44": [
    "Gajaria",
    "Louhajanj",
    "Munshiganj Sadar",
    "Sirajdikhan",
    "Sreenagar",
    "Tongibari"
  ],
  "46": [
    "Baliakandi",
    "Goalanda",
    "Kalukhali",
    "Pangsa",
    "Rajbari Sadar"
  ],
  "48": [
    "Dasar",
    "Kalkini",
    "Madaripur Sadar",
    "Rajoir",
    "Shibchar"
  ],
  "47": [
    "Gopalganj Sadar",
    "Kashiani",
    "Kotalipara",
    "Muksudpur",
    "Tungipara"
  ],
  "45": [
    "Alfadanga",
    "Bhanga",
    "Boalmari",
    "Charbhadrasan",
    "Faridpur Sadar",
    "Madhukhali",
    "Nagarkanda",
    "Sadarpur",
    "Saltha"
  ],
  "01": [
    "Atwari",
    "Boda",
    "Debiganj",
    "Panchagarh Sadar",
    "Tetulia"
  ],
  "03": [
    "Birampur",
    "Birganj",
    "Birol",
    "Bochaganj",
    "Chirirbandar",
    "Dinajpur Sadar",
    "Fulbari",
    "Ghoraghat",
    "Hakimpur",
    "Kaharol",
    "Khansama",
    "Nawabganj",
    "Parbatipur"
  ],
  "05": [
    "Aditmari",
    "Hatibandha",
    "Kaliganj",
    "Lalmonirhat Sadar",
    "Patgram"
  ],
  "04": [
    "Dimla",
    "Domar",
    "Jaldhaka",
    "Kishorganj",
    "Nilphamari Sadar",
    "Syedpur"
  ],
  "08": [
    "Gaibandha Sadar",
    "Gobindaganj",
    "Palashbari",
    "Phulchari",
    "Sadullapur",
    "Saghata",
    "Sundarganj"
  ],
  "02": [
    "Baliadangi",
    "Haripur",
    "Pirganj",
    "Ranisankail",
    "Thakurgaon Sadar"
  ],
  "06": [
    "Badargonj",
    "Gangachara",
    "Kaunia",
    "Mithapukur",
    "Pirgacha",
    "Pirgonj",
    "Rangpur Sadar",
    "Taragonj"
  ],
  "07": [
    "Bhurungamari",
    "Charrajibpur",
    "Chilmari",
    "Kurigram Sadar",
    "Nageshwari",
    "Phulbari",
    "Rajarhat",
    "Rowmari",
    "Ulipur"
  ],
  "35": [
    "Jhenaigati",
    "Nalitabari",
    "Nokla",
    "Sherpur Sadar",
    "Sreebordi"
  ],
  "34": [
    "Bhaluka",
    "Dhobaura",
    "Fulbaria",
    "Gafargaon",
    "Gouripur",
    "Haluaghat",
    "Iswarganj",
    "Muktagacha",
    "Mymensingh Sadar",
    "Nandail",
    "Phulpur",
    "Tarakanda",
    "Trishal"
  ],
  "36": [
    "Bokshiganj",
    "Dewangonj",
    "Islampur",
    "Jamalpur Sadar",
    "Madarganj",
    "Melandah",
    "Sarishabari"
  ],
  "33": [
    "Atpara",
    "Barhatta",
    "Durgapur",
    "Kalmakanda",
    "Kendua",
    "Khaliajuri",
    "Madan",
    "Mohongonj",
    "Netrokona Sadar",
    "Purbadhala"
  ]
};
